<?php
error_reporting ( 0 );
define('ADMIN_UID','1');
define ( 'DBHOST', 'localhost');
define ( 'DBNAME', 'shishice');
define ( 'DBUSER', 'root');
define ( 'DBPASS', 'geeky');
define('DBCHARSET','utf8');
define('CHARSET', 'utf-8');
define('DBTYPE','mysql');
define ( 'TABLEPRE', 's_'); 
define('ENCODE_KEY','keke'); 
define('GZIP',TRUE ); 
define('KEKE_DEBUG', 0);    
define("TPL_CACHE",1);   
define('IS_CACHE',1);
define('CACHE_TYPE', 'file');  
define('ADMIN_DIRECTORY','admin');
define('COOKIE_DOMAIN',''); 
define ( 'COOKIE_PATH', '/ssc/'); 
define('COOKIE_PRE', 'kekeWitkey' );
define('COOKIE_TTL', 0 ); 
define('SESSION_MODULE','files');
define('SYS_START_TIME', time());
$random = explode(' ', microtime());
define("RANDOM_PARA", $random[0]);
function_exists ( 'date_default_timezone_set' ) and date_default_timezone_set ( 'PRC' );
