<?php
  class Keke_witkey_custom_fields_class{
        public $_db;
        public $_tablename;
	    public $_dbop;
	    	 public $_id;  		 public $_f_name; 		 public $_f_code; 		 public $_f_type; 		 public $_f_length; 		 public $_f_decimal_length; 		 public $_f_required; 		 public $_f_tips; 		 public $_f_min_len; 		 public $_f_fixed_len; 		 public $_f_max_len; 		 public $_f_warning; 		 public $_f_regex; 		 public $_model_id; 		 public $_listorder; 
	    public $_cache_config = array ('is_cache' => 0, 'time' => 0 );
	    public $_replace=0;  
	    public $_where;      
	     function  keke_witkey_custom_fields_class(){ 			 $this->_db = new db_factory ( );			 $this->_dbop = $this->_db->create(DBTYPE);			 $this->_tablename = TABLEPRE."witkey_custom_fields";		 }	    
	    		public function getId(){			 return $this->_id ;		}		public function getF_name(){			 return $this->_f_name ;		}		public function getF_code(){			 return $this->_f_code ;		}		public function getF_type(){			 return $this->_f_type ;		}		public function getF_length(){			 return $this->_f_length ;		}		public function getF_decimal_length(){			 return $this->_f_decimal_length ;		}		public function getF_required(){			 return $this->_f_required ;		}		public function getF_tips(){			 return $this->_f_tips ;		}		public function getF_min_len(){			 return $this->_f_min_len ;		}		public function getF_fixed_len(){			 return $this->_f_fixed_len ;		}		public function getF_max_len(){			 return $this->_f_max_len ;		}		public function getF_warning(){			 return $this->_f_warning ;		}		public function getF_regex(){			 return $this->_f_regex ;		}		public function getModel_id(){			 return $this->_model_id ;		}		public function getListorder(){			 return $this->_listorder ;		}		public function getWhere(){			 return $this->_where ;		}		public function getCache_config() {			return $this->_cache_config;		}
	    		public function setId($value){ 			 $this->_id = $value;		}		public function setF_name($value){ 			 $this->_f_name = $value;		}		public function setF_code($value){ 			 $this->_f_code = $value;		}		public function setF_type($value){ 			 $this->_f_type = $value;		}		public function setF_length($value){ 			 $this->_f_length = $value;		}		public function setF_decimal_length($value){ 			 $this->_f_decimal_length = $value;		}		public function setF_required($value){ 			 $this->_f_required = $value;		}		public function setF_tips($value){ 			 $this->_f_tips = $value;		}		public function setF_min_len($value){ 			 $this->_f_min_len = $value;		}		public function setF_fixed_len($value){ 			 $this->_f_fixed_len = $value;		}		public function setF_max_len($value){ 			 $this->_f_max_len = $value;		}		public function setF_warning($value){ 			 $this->_f_warning = $value;		}		public function setF_regex($value){ 			 $this->_f_regex = $value;		}		public function setModel_id($value){ 			 $this->_model_id = $value;		}		public function setListorder($value){ 			 $this->_listorder = $value;		}		public function setWhere($value){ 			 $this->_where = $value;		}		public function setCache_config($_cache_config) {			 $this->_cache_config = $_cache_config; 		}
    	   public  function __set($property_name, $value) {
		 		$this->$property_name = $value; 
			}
			public function __get($property_name) { 
				if (isset ( $this->$property_name )) { 
					return $this->$property_name; 
				} else { 
					return null; 
				} 
			}
	    		function create_keke_witkey_custom_fields(){		 		 $data =  array(); 					if(!is_null($this->_id)){ 				 $data['id']=$this->_id;			}			if(!is_null($this->_f_name)){ 				 $data['f_name']=$this->_f_name;			}			if(!is_null($this->_f_code)){ 				 $data['f_code']=$this->_f_code;			}			if(!is_null($this->_f_type)){ 				 $data['f_type']=$this->_f_type;			}			if(!is_null($this->_f_length)){ 				 $data['f_length']=$this->_f_length;			}			if(!is_null($this->_f_decimal_length)){ 				 $data['f_decimal_length']=$this->_f_decimal_length;			}			if(!is_null($this->_f_required)){ 				 $data['f_required']=$this->_f_required;			}			if(!is_null($this->_f_tips)){ 				 $data['f_tips']=$this->_f_tips;			}			if(!is_null($this->_f_min_len)){ 				 $data['f_min_len']=$this->_f_min_len;			}			if(!is_null($this->_f_fixed_len)){ 				 $data['f_fixed_len']=$this->_f_fixed_len;			}			if(!is_null($this->_f_max_len)){ 				 $data['f_max_len']=$this->_f_max_len;			}			if(!is_null($this->_f_warning)){ 				 $data['f_warning']=$this->_f_warning;			}			if(!is_null($this->_f_regex)){ 				 $data['f_regex']=$this->_f_regex;			}			if(!is_null($this->_model_id)){ 				 $data['model_id']=$this->_model_id;			}			if(!is_null($this->_listorder)){ 				 $data['listorder']=$this->_listorder;			}			 return $this->_id = $this->_db->inserttable($this->_tablename,$data,1,$this->_replace); 		 } 
	    		function edit_keke_witkey_custom_fields(){ 		 		 $data =  array();  					if(!is_null($this->_id)){ 				 $data['id']=$this->_id;			}			if(!is_null($this->_f_name)){ 				 $data['f_name']=$this->_f_name;			}			if(!is_null($this->_f_code)){ 				 $data['f_code']=$this->_f_code;			}			if(!is_null($this->_f_type)){ 				 $data['f_type']=$this->_f_type;			}			if(!is_null($this->_f_length)){ 				 $data['f_length']=$this->_f_length;			}			if(!is_null($this->_f_decimal_length)){ 				 $data['f_decimal_length']=$this->_f_decimal_length;			}			if(!is_null($this->_f_required)){ 				 $data['f_required']=$this->_f_required;			}			if(!is_null($this->_f_tips)){ 				 $data['f_tips']=$this->_f_tips;			}			if(!is_null($this->_f_min_len)){ 				 $data['f_min_len']=$this->_f_min_len;			}			if(!is_null($this->_f_fixed_len)){ 				 $data['f_fixed_len']=$this->_f_fixed_len;			}			if(!is_null($this->_f_max_len)){ 				 $data['f_max_len']=$this->_f_max_len;			}			if(!is_null($this->_f_warning)){ 				 $data['f_warning']=$this->_f_warning;			}			if(!is_null($this->_f_regex)){ 				 $data['f_regex']=$this->_f_regex;			}			if(!is_null($this->_model_id)){ 				 $data['model_id']=$this->_model_id;			}			if(!is_null($this->_listorder)){ 				 $data['listorder']=$this->_listorder;			}			if($this->_where){ 				 return $this->_db->updatetable($this->_tablename,$data,$this->getWhere()); 			 } 			 else{ 				 $where = array('id' => $this->_id); 				 return $this->_db->updatetable($this->_tablename,$data,$where); 			} 		 } 
	    		function query_keke_witkey_custom_fields($is_cache=0, $cache_time=0){ 			 if($this->_where){ 				 $sql = "select * from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "select * from $this->_tablename"; 			 } 			if ($is_cache) {			 $this->_cache_config ['is_cache'] = $is_cache;			}			if ($cache_time) {			 $this->_cache_config ['time'] = $cache_time;			 }			 if ($this->_cache_config ['is_cache']) {			     if (CACHE_TYPE) {					 $keke_cache = new keke_cache_class ( CACHE_TYPE );					 $id = $this->_tablename . ($this->_where?"_" .substr(md5 ( $this->_where ),0,6):'');						$data = $keke_cache->get ( $id );							if ($data) {								return $data; 							} else { 								$res = $this->_dbop->query ( $sql ); 								$keke_cache->set ( $id, $res,$this->_cache_config['time'] ); 					 			$this->_where = ""; 								return $res; 							} 						} 			 }else{			 	$this->_where = ""; 				return  $this->_dbop->query ( $sql ); 			 }		 } 
	    		function count_keke_witkey_custom_fields(){ 			 if($this->_where){ 				 $sql = "select count(*) as count from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "select count(*) as count from $this->_tablename"; 			 } 			 $this->_where = ""; 			 return $this->_dbop->getCount($sql); 		 } 
	    		function del_keke_witkey_custom_fields(){ 			 if($this->_where){ 				 $sql = "delete from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "delete from $this->_tablename where id = $this->_id "; 			 } 			 $this->_where = ""; 			 return $this->_dbop->execute($sql); 		 } 
   }
 ?>