<?php
  class Keke_witkey_get_password_log_class{
        public $_db;
        public $_tablename;
	    public $_dbop;
	    	 public $_id;  		 public $_valid_type; 		 public $_get_uid; 		 public $_valid_code; 		 public $_send_from; 		 public $_send_time; 		 public $_expire_time; 		 public $_valid_status; 		 public $_encrypteuid; 		 public $_authsid; 
	    public $_cache_config = array ('is_cache' => 0, 'time' => 0 );
	    public $_replace=0;  
	    public $_where;      
	     function  keke_witkey_get_password_log_class(){ 			 $this->_db = new db_factory ( );			 $this->_dbop = $this->_db->create(DBTYPE);			 $this->_tablename = TABLEPRE."witkey_get_password_log";		 }	    
	    		public function getId(){			 return $this->_id ;		}		public function getValid_type(){			 return $this->_valid_type ;		}		public function getGet_uid(){			 return $this->_get_uid ;		}		public function getValid_code(){			 return $this->_valid_code ;		}		public function getSend_from(){			 return $this->_send_from ;		}		public function getSend_time(){			 return $this->_send_time ;		}		public function getExpire_time(){			 return $this->_expire_time ;		}		public function getValid_status(){			 return $this->_valid_status ;		}		public function getEncrypteuid(){			 return $this->_encrypteuid ;		}		public function getAuthsid(){			 return $this->_authsid ;		}		public function getWhere(){			 return $this->_where ;		}		public function getCache_config() {			return $this->_cache_config;		}
	    		public function setId($value){ 			 $this->_id = $value;		}		public function setValid_type($value){ 			 $this->_valid_type = $value;		}		public function setGet_uid($value){ 			 $this->_get_uid = $value;		}		public function setValid_code($value){ 			 $this->_valid_code = $value;		}		public function setSend_from($value){ 			 $this->_send_from = $value;		}		public function setSend_time($value){ 			 $this->_send_time = $value;		}		public function setExpire_time($value){ 			 $this->_expire_time = $value;		}		public function setValid_status($value){ 			 $this->_valid_status = $value;		}		public function setEncrypteuid($value){ 			 $this->_encrypteuid = $value;		}		public function setAuthsid($value){ 			 $this->_authsid = $value;		}		public function setWhere($value){ 			 $this->_where = $value;		}		public function setCache_config($_cache_config) {			 $this->_cache_config = $_cache_config; 		}
    	   public  function __set($property_name, $value) {
		 		$this->$property_name = $value; 
			}
			public function __get($property_name) { 
				if (isset ( $this->$property_name )) { 
					return $this->$property_name; 
				} else { 
					return null; 
				} 
			}
	    		function create_keke_witkey_get_password_log(){		 		 $data =  array(); 					if(!is_null($this->_id)){ 				 $data['id']=$this->_id;			}			if(!is_null($this->_valid_type)){ 				 $data['valid_type']=$this->_valid_type;			}			if(!is_null($this->_get_uid)){ 				 $data['get_uid']=$this->_get_uid;			}			if(!is_null($this->_valid_code)){ 				 $data['valid_code']=$this->_valid_code;			}			if(!is_null($this->_send_from)){ 				 $data['send_from']=$this->_send_from;			}			if(!is_null($this->_send_time)){ 				 $data['send_time']=$this->_send_time;			}			if(!is_null($this->_expire_time)){ 				 $data['expire_time']=$this->_expire_time;			}			if(!is_null($this->_valid_status)){ 				 $data['valid_status']=$this->_valid_status;			}			if(!is_null($this->_encrypteuid)){ 				 $data['encrypteuid']=$this->_encrypteuid;			}			if(!is_null($this->_authsid)){ 				 $data['authsid']=$this->_authsid;			}			 return $this->_id = $this->_db->inserttable($this->_tablename,$data,1,$this->_replace); 		 } 
	    		function edit_keke_witkey_get_password_log(){ 		 		 $data =  array();  					if(!is_null($this->_id)){ 				 $data['id']=$this->_id;			}			if(!is_null($this->_valid_type)){ 				 $data['valid_type']=$this->_valid_type;			}			if(!is_null($this->_get_uid)){ 				 $data['get_uid']=$this->_get_uid;			}			if(!is_null($this->_valid_code)){ 				 $data['valid_code']=$this->_valid_code;			}			if(!is_null($this->_send_from)){ 				 $data['send_from']=$this->_send_from;			}			if(!is_null($this->_send_time)){ 				 $data['send_time']=$this->_send_time;			}			if(!is_null($this->_expire_time)){ 				 $data['expire_time']=$this->_expire_time;			}			if(!is_null($this->_valid_status)){ 				 $data['valid_status']=$this->_valid_status;			}			if(!is_null($this->_encrypteuid)){ 				 $data['encrypteuid']=$this->_encrypteuid;			}			if(!is_null($this->_authsid)){ 				 $data['authsid']=$this->_authsid;			}			if($this->_where){ 				 return $this->_db->updatetable($this->_tablename,$data,$this->getWhere()); 			 } 			 else{ 				 $where = array('id' => $this->_id); 				 return $this->_db->updatetable($this->_tablename,$data,$where); 			} 		 } 
	    		function query_keke_witkey_get_password_log($is_cache=0, $cache_time=0){ 			 if($this->_where){ 				 $sql = "select * from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "select * from $this->_tablename"; 			 } 			if ($is_cache) {			 $this->_cache_config ['is_cache'] = $is_cache;			}			if ($cache_time) {			 $this->_cache_config ['time'] = $cache_time;			 }			 if ($this->_cache_config ['is_cache']) {			     if (CACHE_TYPE) {					 $keke_cache = new keke_cache_class ( CACHE_TYPE );					 $id = $this->_tablename . ($this->_where?"_" .substr(md5 ( $this->_where ),0,6):'');						$data = $keke_cache->get ( $id );							if ($data) {								return $data; 							} else { 								$res = $this->_dbop->query ( $sql ); 								$keke_cache->set ( $id, $res,$this->_cache_config['time'] ); 					 			$this->_where = ""; 								return $res; 							} 						} 			 }else{			 	$this->_where = ""; 				return  $this->_dbop->query ( $sql ); 			 }		 } 
	    		function count_keke_witkey_get_password_log(){ 			 if($this->_where){ 				 $sql = "select count(*) as count from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "select count(*) as count from $this->_tablename"; 			 } 			 $this->_where = ""; 			 return $this->_dbop->getCount($sql); 		 } 
	    		function del_keke_witkey_get_password_log(){ 			 if($this->_where){ 				 $sql = "delete from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "delete from $this->_tablename where id = $this->_id "; 			 } 			 $this->_where = ""; 			 return $this->_dbop->execute($sql); 		 } 
   }
 ?>